### ISSUE TITLE
Implementing Glue Schema Registry using Helm

### ISSUE THREAD

**Issue by fcanas-endava** [provectus/kafka-ui-charts#14]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/provectus/kafka-ui/issues) and [here](https://github.com/provectus/kafka-ui-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hey guys,

I have an already running Kafka UI within an EKS cluster and would like to implement Glue Schema Registry in the same Helm deployment. Is this supported? I saw that there's some documentation using docker compose but couldnt find anything related to Helm. 

Thanks. 

### Your installation details

*

### Steps to reproduce

*

**Comment by Haarolean** [comment]
Hey, sorry for the delay! Figured out I wasn't subscribed to this repo yet :))

Unfortunately, that's not supported in any way with charts, as you even need to extend the base image to include custom serdes, one of which glue is.
We're not planning either including glue in the base image or extending charts to support this.
On the other hand, we plan to ship one more AMI image like [the one we have](https://aws.amazon.com/marketplace/pp/prodview-ogtt5hfhzkq6a), but with all enterprise serdes included (glue, for example) and enabled by default.
Also, if you're willing to introduce better support for external serdes in the charts, PRs are welcome :)
